### ISSUE TITLE
Homekit

### ISSUE THREAD

**Issue by findthebug** [AzonInc/Doorman#46]
### Description

Support to connect the door opener action to homekit would be super.

Since this is using ESP maybe there is a way to integrate HomeSpan, so the actions like doorbell, opener are exposed to homekit.

looking for a way to controll Koch TC50, door opener with homekit. This project looks promising to me. 

also using Homebridge, maybe there is a way to connect Doorman with a plugin there?

**Comment by AzonInc** [comment]
There is a Homebridge plugin: https://github.com/matomato13/homebridge-esphome-doorbell
This should allow you to select the ESPHome doorbell binary sensor to detect the doorbell via doorman.
This could be a starting point to support doorman via homekit.

Needs some modification to support the door opener action but basically supports the doorbell detection.

**Comment by findthebug** [comment]
if i see this correctly. there is a firmware for doorman & MQTT only right? Homebridge has also some MQTT plugins, maybe it's even easier to communicate directly with doorman?

**Comment by AzonInc** [comment]
Yea I saw that as well but you would need to add the entire topic structure to your config and build it. Doing that can be quite a pain with esphome but you can also give it a try.

**Comment by findthebug** [comment]
at the end all im looking for is a way to trigger door opener in some way. since the doorman has an IP address, is there a chance to just do some simple curl to trigger door opener?

**Comment by AzonInc** [comment]
Yes of course, you can use the ESPHome API and make a call to toggle the button.

```
Request URL:
http://IP/button/open_entrance_door/press

Request Method:
POST
```

```
curl -X POST http://IP/button/open_entrance_door/press
```

**Comment by findthebug** [comment]
Ah ok. Do i need Home Assistant setup for this? Or is there a firmware i can implement this without HA?

**Comment by AzonInc** [comment]
You don't need Home Assistant for it, just use the custom config and add the ESPHome API again. If you need an example I can help you. There are three config types, HA, MQTT and Custom

```yaml
# Doorman Stock Firmware (CUSTOM)
# Base Board ESP32-S3

# You can change a few options here.
substitutions:
  name: "doorman-s3"
  friendly_name: "Doorman S3"

# Import Doorman Firmware Config
packages:
  AzonInc.Doorman: github://azoninc/doorman/firmware/configurations/esp32-s3.custom.stock.master.yaml@master

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  reboot_timeout: 0s
```
