### ISSUE TITLE
Muting the apartment station/door bell

### ISSUE THREAD

**Issue by Nerdiyde** [AzonInc/Doorman#48]
### Description

Hi guys,
not 100% a feature request (yet):

Does anybody know if it is possible to use doorman to mute the station/doorbell within the apartment. 
So far I could not observe that there is a bus command sent when the mute button on the panel is pressed.
Probably there is a GPIO on the panel that could be used? Does anybody know something about that?

The idea is that I could automatically mute the bell in case my smart home is in a certain mode (sleep, etc).

Thanks in advance and best regards
Fab

**Comment by AzonInc** [comment]
There's no straightforward way to achieve this.
Someone is using the Doorman relay to disconnect the indoor station's speaker in order to mute it.

Although it's possible to read and write the mute state, the indoor station doesn't accept changes to that setting.
As a workaround, we might be able to send a series of dummy commands to suppress the ringtone.

Update:
Sending a lot of data over the bus will degrade or suppress the ringtone output (50%).

```yaml
binary_sensor:
  - id: !extend apartment_doorbell
    on_press:
      - lambda: |-
          for (int i = 0; i < 25; ++i) {
            id(tc_bus_intercom)->send_command(0x9FFFFFFF, true, 10);
          }
      - delay: 3s
      - tc_bus.send:
          type: reset
```

Combining this with the settings (ringtone volume) it should be better than nothing
