### ISSUE TITLE
Stability issue with release 2025.3.0?

### ISSUE THREAD

**Issue by Nerdiyde** [AzonInc/Doorman#55]
### Description

I recently upgraded to Doorman release 2025.3.0 and observed that there seems to be a stability issue. Please see the attached screenshot of the uptime entity.

![Image](https://github.com/user-attachments/assets/701d3a8b-959f-4996-89ad-c0fd042d2f7c)

Since I installed the new release (aprox. 11. of  june in the screenshot of the uptime entity) I had several reebots.

The earlier release had a runtime of ~23 days when I installed the new release. 

Intersting point: There is a longer period of no reboots which fits to a period where I was not at home. So probably the issue (trigger of reboots) corelates with any events like door bell or door openings (which were reduced while I was not at home).

Also installed now the latest version of ESPHome Device Builder to see if this fixes the issue.

Please let me know which additional info I can provide. :)
Thanks in advance!

### Logs

```plain text
Don't have any logs available. Thinking about adding the Syslog component (https://esphome.io/components/syslog.html) to collect more info. Do you think that makes sense?
```

### Which version of the ESPHome Doorman firmware config are you running?

2025.3.0

### How do you manage your Doorman's updates?

ESPHome YAML Config

### If you're using an ESPHome YAML config, which version of ESPHome are you running?

2025.5.1

### ESPHome Config

```YAML
I adopted the original release but did not change it yet.
Nevertheless:

# Doorman Stock Firmware (Home Assistant)
# Base Board ESP32-S3-QUAD

# You can change a few options here.
substitutions:
  name: "doorman-s3"
  friendly_name: "Doorman S3"
  # log_level: "ERROR"
  # led_pin: "GPIO1"
  # rgb_led_pin: "GPIO2"
  # relay_pin: "GPIO42"
  # external_button_pin: "GPIO41"
  # adc_input_pin: "GPIO10"

# Import Doorman Firmware Config
packages:
  AzonInc.Doorman: github://azoninc/doorman/firmware/configurations/esp32-s3-quad.ha.stock.master.yaml@master

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

**Comment by AzonInc** [comment]
Which version did u use before updating? ESPHome as well as Doorman.
It seems to be a known issue, however I couldn't find the issue yet.

After while something is causing the internal RAM to spike and the it's crashing.
If you monitor restart reason and heap size, max heap block and other entites at the same time you will see a pattern.

However these entities don't exist in the stable version.

I think you can add them using this modified config:
```
# Doorman Stock Firmware (Home Assistant)
# Base Board ESP32-S3-QUAD

# You can change a few options here.
substitutions:
  name: "doorman-s3"
  friendly_name: "Doorman S3"

packages:
  AzonInc.Doorman: github://azoninc/doorman/firmware/configurations/esp32-s3-quad.ha.stock.master.yaml@master
  debug_utilities: github://azoninc/doorman/firmware/components/debug-utilities.yaml@master
  debug_utilities_psram: github://azoninc/doorman/firmware/components/debug-utilities.psram.yaml@master

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

You could also try the dev version which changes the implementation. But I think the issue persists.
Please read the changelog as this really changes a lot. 
```
# Doorman Stock Firmware (Home Assistant)
# Base Board ESP32-S3-QUAD

# You can change a few options here.
substitutions:
  name: "doorman-s3"
  friendly_name: "Doorman S3"

packages:
  AzonInc.Doorman: github://azoninc/doorman/firmware/configurations/esp32-s3-quad.ha.stock.dev.yaml@dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

**Comment by Nerdiyde** [comment]
Not really sure if I can specify the correct version of the doorman firmware here since I pulled the stuff I needed and build my "own" yaml. 

The content is the following:

```
esphome:
  name: doorman
  friendly_name: Doorman
  
  min_version: "2024.8.0"

  on_boot:
    then:
      - light.turn_on:
          id: doorman_rgb_status_led
          effect: pulse
          red: 0%
          green: 56%
          blue: 52%
          brightness: 60%
      - wait_until:
          condition:
            wifi.connected:
      - light.turn_on:
          id: doorman_rgb_status_led
          effect: slow_pulse
          red: 0%
          green: 50%
          blue: 100%
          brightness: 60%
      - wait_until:
          condition:
            api.connected:
      - light.turn_on:
          id: doorman_rgb_status_led
          effect: none
          red: 0%
          green: 50%
          blue: 100%
          brightness: 60%
      - delay: 3s
      - script.execute: update_led
      
  platformio_options:
    board_build.flash_mode: dio

# Board Setup
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 0s
  encryption:
    key: !secret doorman_api_key
  services:
    - service: send_tcs_command
      variables:
        command: int
      then:
        - tcs_intercom.send:
            command: !lambda 'return command;'

web_server:
  version: 3
  port: 80
  auth:
    username: !secret doorman_web_server_user
    password: !secret doorman_web_server_password

ota:
  platform: esphome
  password: !secret doorman_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Doorman Fallback Hotspot"
    password: !secret doorman_ap_password

captive_portal:

# Configurable Options
substitutions:
  name: "doorman-s3"
  friendly_name: "Doorman S3"
  log_level: "ERROR"

  # Hardware Configuration
  led_pin: "GPIO1"
  rgb_led_pin: "GPIO2"

  # TCS Commands
  apartment_doorbell_command: "0x130efe41"
  entrance_doorbell_command: "0x030efe80"
  entrance_door_opener_command: "0x1100"

  # Party Mode Settings
  party_mode_door_opener_delay: "70ms"

# Improv Provisioning
improv_serial:

# Import TCS Intercom Component
external_components:
  - source:
      type: git
      url: https://github.com/AzonInc/esphome_tcs_intercom
      ref: master
    components: [ tcs_intercom ]
    refresh: 60s

# Setup TCS Intercom Component
tcs_intercom:
  bus_command:
    name: "Last Bus Command"
    disabled_by_default: true
  hardware_version:
    name: "Hardware"
    icon: "mdi:router-wireless"
    disabled_by_default: true

select:
  - platform: template
    id: doorman_ring_to_open_timeout_mode
    name: "Ring To Open: Timeout"
    icon: mdi:clock-fast
    optimistic: true
    options:
      - Never
      - Ring once
      - 5 minutes
      - 10 minutes
      - 15 minutes
      - 20 minutes
      - 25 minutes
      - 30 minutes
      - 35 minutes
      - 40 minutes
      - 45 minutes
      - 50 minutes
      - 55 minutes
      - 60 minutes
    initial_option: Never
    entity_category: CONFIG
    disabled_by_default: true

switch:
  # Preconfigured Ring To Open Mode Switch
  - platform: template
    name: Ring To Open
    icon: mdi:party-popper
    id: doorman_ring_to_open
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    #turn_on_action:
    #  - script.execute: ring_to_open_timer
    #turn_off_action:
    #  - script.stop: ring_to_open_timer
    #on_turn_on:
    #  - script.execute: update_led
    #on_turn_off:
    #  - script.execute: update_led

  - platform: template
    name: "Ring To Open: Confirmation"
    icon: mdi:bell-check
    id: doorman_ring_to_open_confirmation
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    entity_category: CONFIG
    disabled_by_default: true

  # Preconfigured Party Mode Switch
  - platform: template
    name: Party Mode
    icon: mdi:party-popper
    id: doorman_party_mode
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    disabled_by_default: true
    turn_on_action:
      - light.turn_on:
          id: doorman_rgb_status_led
          red: 80%
          green: 80%
          blue: 3%
          effect: slow_pulse
          brightness: 60%
    turn_off_action:
      - light.turn_off: doorman_rgb_status_led

button:
  # System Actions
  - platform: restart
    entity_category: config
    name: Restart
    icon: mdi:restart
    disabled_by_default: true

  - platform: safe_mode
    name: Safe mode
    entity_category: config
    disabled_by_default: true

  # Preconfigured Door Opener Button
  - platform: template
    name: "Haustür öffnen"
    id : "open_entrance_door_button"
    icon: mdi:door
    on_press:
      - tcs_intercom.send:
          command: ${entrance_door_opener_command}

# Onboard Status LEDs
light:
  - platform: status_led
    id: doorman_status_led
    name: Status LED
    pin: ${led_pin}
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config

  - platform: esp32_rmt_led_strip
    id: doorman_rgb_status_led
    internal: true
    restore_mode: ALWAYS_OFF
    rgb_order: GRB
    pin: ${rgb_led_pin}
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    gamma_correct: 1
    default_transition_length: 0ms
    color_correct: [60%, 60%, 60%]
    effects:
      - pulse:
          name: pulse
          transition_length: 250ms
          update_interval: 250ms
      - pulse:
          name: slow_pulse
          transition_length: 1s
          update_interval: 2s
      - pulse:
          name: slow_partymode
          transition_length: 3s
          update_interval: 3s

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"

  - platform: uptime
    name: Uptime

binary_sensor:
  - platform: status
    id: api_connection
    filters:
      - delayed_on: 1s
    on_press:
      - lambda: |
          ESP_LOGD("api", "API Connected");
    on_release:
      - lambda: |
          ESP_LOGD("api", "API Disconnected");
          
  # Preconfigured Party Mode Action (Internal)
  - platform: tcs_intercom
    id: doorman_entrance_doorbell
    command: ${entrance_doorbell_command}
    internal: true
    on_press:
      then:
        - if:
            condition:
              switch.is_on: doorman_party_mode
            then:
              - delay: ${party_mode_door_opener_delay}
              - tcs_intercom.send:
                  command: ${entrance_door_opener_command}

  # Preconfigured Sensors
  - platform: tcs_intercom
    name: "Haustür Klingel"
    id: "entrance_doorbell_sensor"
    command: ${entrance_doorbell_command}
    device_class: sound

  - platform: tcs_intercom
    name: "Wohnungstür Klingel"
    id: "apartement_doorbell_sensor"
    command: ${apartment_doorbell_command}
    device_class: sound

script:
  - id: update_led
    then:
      # TODO: Restore specific state conditionally
      - if:
          condition:
            - switch.is_on: doorman_ring_to_open
          then:
            - light.turn_on:
                id: doorman_rgb_status_led
                red: 100%
                green: 100%
                blue: 3%
                effect: slow_pulse
          else:
            - light.turn_off:
                id: doorman_rgb_status_led
                transition_length: 1s
```

I just added the modifications for the stable version again and will observe this. I will come back with feedback in some days. 
Thanks and best regards
